hpc<-read.table("household_power_consumption.txt",sep=";", header=TRUE,na.strings="?")
hpc$DateTime<-strptime(paste(hpc$Date,hpc$Time),"%d/%m/%Y %H:%M:%S")
hpcFiltered<-subset(hpc, DateTime > "2007-02-01" & DateTime < "2007-02-03")
with (hpcFiltered, plot(DateTime,Global_active_power,type="l",ylab="Global Active Power (kilowatts)",xlab=""))
dev.copy(png,file="plot2.png")
dev.off()